version: '3.8'

name: portfolio

services:
  backend:
    build: ./src/Server
    restart: unless-stopped
    env_file: ./src/Server/.env
    ports:
      - "3000:3000"
      

  frontend:
    build: ./src
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend